### ISSUE TITLE
backlog

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-crud-standard#18]
# Backlog
 
## Travail à faire
Liste des tâches
Création des fichiers de description des tâches

## Gestion de lab 

- En démarrage de la tâche 
  - Ajoutez label `en_cours` à l'issue en démarrage de la tâche
  - Création de fichier doc/base-de-données.md
  - Création de pullrequest qui permet de fermer l'issue, avec le nom de la tâche
- En fin de la tâche
  - Supprimer le label `en_cours`
  - Ajouter le label `en_validation`

## Livrable 
- backlog/feature/*
- Fichier README.md

**Comment by husseinbouik** [comment]
- L'issue n'est pas liée avec une pull request ouverte
