### ISSUE TITLE
init-lab

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-crud-standard#19]
# Init lab

## Travail à faire

- Création d'un rapport et présentation sans contenu avec les pages et leurs titres

## Livrable
- docs/index.md
- docs/présentation.md

**Comment by husseinbouik** [comment]
- la description de la tâche n'est pas valide

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue
